#ifndef __KERNEL_C_DEFINITION_STD_BOOL_HEADER__
#define __KERNEL_C_DEFINITION_STD_BOOL_HEADER__

#ifdef __KERNEL_BOOL_IS_UNSIGNED_CHAR_TYPE
    typedef unsigned char bool_t;
#endif

#endif /* __KERNEL_C_DEFINITION_STD_BOOL_HEADER__ */