#ifndef __KERNEL_C_DEFINITION_STD_NONSTANDARD_VOLATILE_PAUSEWHILE__
#define __KERNEL_C_DEFINITION_STD_NONSTANDARD_VOLATILE_PAUSEWHILE__
#include <stdint.h>


void pausewhile(volatile uint8_t condition);


#endif /* __KERNEL_C_DEFINITION_STD_NONSTANDARD_VOLATILE_PAUSEWHILE__ */