#ifndef __KERNEL_C_DEFINITION_PREBOOT_FRAMEBUFFER_EXPORT_HEADER__
#define __KERNEL_C_DEFINITION_PREBOOT_FRAMEBUFFER_EXPORT_HEADER__
#ifndef __KERNEL_CONSOLE_VEC2_UNSIGNED_SHORT_TYPE
#   define __KERNEL_CONSOLE_VEC2_UNSIGNED_SHORT_TYPE
#endif
#ifndef __KERNEL_CONSOLE_FRAMEBUFFER_TYPE
#   define __KERNEL_CONSOLE_FRAMEBUFFER_TYPE
#endif
#ifndef __KERNEL_CONSOLE_RGB32_UNION_TYPE
#   define __KERNEL_CONSOLE_RGB32_UNION_TYPE
#endif
#include <gpcs2/types.h>


#endif /* __KERNEL_C_DEFINITION_PREBOOT_FRAMEBUFFER_EXPORT_HEADER__ */