
//
// Bitmap font C header file generated by bmfont2c.py 
// 

#ifndef FONTLIBRARY_H_
#define FONTLIBRARY_H_

#include <stdint.h>

typedef struct
{
    char_t GlyphCount;
    char_t FirstAsciiCode;
    char_t GlyphBytesWidth;
    char_t GlyphHeight;
    char_t FixedWidth;
    char_t const *GlyphWidth;
    char_t const *GlyphBitmaps;
} fontStyle_t;


extern fontStyle_t FontStyle_Consolas12;

#endif /* FONTLIBRARY_H_ */
