
//
// Bitmap font C header file generated by bmfont2c.py 
// 

#ifndef FONTLIBRARY_H_
#define FONTLIBRARY_H_

#include <stdint.h>

typedef struct
{
    char GlyphCount;
    char FirstAsciiCode;
    char GlyphBytesWidth;
    char GlyphHeight;
    char FixedWidth;
    char const *GlyphWidth;
    char const *GlyphBitmaps;
} fontStyle_t;


extern fontStyle_t FontStyle_Consolas12;

#endif /* FONTLIBRARY_H_ */
